export const DEFAULT_SETTINGS: CodeBlocksPluginSettings = {
  showAliasLabels: false,
  customLanguages: [],
  usedCount: {},
};

export const sourceLanguages: LanguageCode[] = [
  { markup: "abap", lang: "ABAP" },
  { markup: "abnf", lang: "ABNF" },
  { markup: "actionscript", lang: "ActionScript" },
  { markup: "ada", lang: "Ada" },
  { markup: "adoc", lang: "AsciiDoc", isAlias: true },
  { markup: "agda", lang: "Agda" },
  { markup: "al", lang: "AL" },
  { markup: "antlr4", lang: "ANTLR4" },
  { markup: "apacheconf", lang: "Apache Configuration" },
  { markup: "apex", lang: "Apex" },
  { markup: "apl", lang: "APL" },
  { markup: "applescript", lang: "AppleScript" },
  { markup: "aql", lang: "AQL" },
  { markup: "arduino", lang: "Arduino" },
  { markup: "arff", lang: "ARFF" },
  { markup: "arm-asm", lang: "ARM Assembly", isAlias: true },
  { markup: "armasm", lang: "ARM Assembly" },
  { markup: "art", lang: "Arturo", isAlias: true },
  { markup: "arturo", lang: "Arturo" },
  { markup: "asciidoc", lang: "AsciiDoc" },
  { markup: "asm6502", lang: "6502 Assembly" },
  { markup: "asmatmel", lang: "Atmel AVR Assembly" },
  { markup: "aspnet", lang: "ASP.NET (C#)" },
  { markup: "atom", lang: "XML", title: "Atom", isAlias: true },
  { markup: "autohotkey", lang: "AutoHotkey" },
  { markup: "autoit", lang: "AutoIt" },
  { markup: "avdl", lang: "Avro IDL", isAlias: true },
  { markup: "avisynth", lang: "AviSynth" },
  { markup: "avro-idl", lang: "Avro IDL" },
  { markup: "avs", lang: "AviSynth", isAlias: true },
  { markup: "awk", lang: "AWK" },
  { markup: "bash", lang: "Bash" },
  { markup: "basic", lang: "BASIC" },
  { markup: "batch", lang: "Batch" },
  { markup: "bbcode", lang: "BBcode" },
  { markup: "bbj", lang: "BBj" },
  { markup: "bicep", lang: "Bicep" },
  { markup: "birb", lang: "Birb" },
  { markup: "bison", lang: "Bison" },
  { markup: "bnf", lang: "BNF" },
  { markup: "bqn", lang: "BQN" },
  { markup: "brainfuck", lang: "Brainfuck" },
  { markup: "brightscript", lang: "BrightScript" },
  { markup: "bro", lang: "Bro" },
  { markup: "bsl", lang: "BSL (1C:Enterprise)" },
  { markup: "c", lang: "C" },
  { markup: "cfc", lang: "CFScript", isAlias: true },
  { markup: "cfscript", lang: "CFScript" },
  { markup: "chaiscript", lang: "ChaiScript" },
  { markup: "cil", lang: "CIL" },
  { markup: "cilk", lang: "Cilk/C++", isAlias: true },
  { markup: "cilk-c", lang: "Cilk/C", isAlias: true },
  { markup: "cilk-cpp", lang: "Cilk/C++", isAlias: true },
  { markup: "cilkc", lang: "Cilk/C" },
  { markup: "cilkcpp", lang: "Cilk/C++" },
  { markup: "clike", lang: "C-like" },
  { markup: "clojure", lang: "Clojure" },
  { markup: "cmake", lang: "CMake" },
  { markup: "cobol", lang: "COBOL" },
  { markup: "coffee", lang: "CoffeeScript", isAlias: true },
  { markup: "coffeescript", lang: "CoffeeScript" },
  { markup: "conc", lang: "Concurnas", isAlias: true },
  { markup: "concurnas", lang: "Concurnas" },
  { markup: "context", lang: "LaTeX", title: "ConTeXt", isAlias: true },
  { markup: "cooklang", lang: "Cooklang" },
  { markup: "coq", lang: "Coq" },
  { markup: "cpp", lang: "C++" },
  { markup: "crystal", lang: "Crystal" },
  { markup: "cs", lang: "C#", isAlias: true },
  { markup: "csharp", lang: "C#" },
  { markup: "cshtml", lang: "Razor C#" },
  { markup: "csp", lang: "Content-Security-Policy" },
  { markup: "css", lang: "CSS" },
  { markup: "css-extras", lang: "CSS Extras" },
  { markup: "css-selector", lang: "CSS Selector" },
  { markup: "csv", lang: "CSV" },
  { markup: "cue", lang: "CUE" },
  { markup: "cypher", lang: "Cypher" },
  { markup: "d", lang: "D" },
  { markup: "dart", lang: "Dart" },
  { markup: "dataweave", lang: "DataWeave" },
  { markup: "dax", lang: "DAX" },
  { markup: "dhall", lang: "Dhall" },
  { markup: "diff", lang: "Diff" },
  { markup: "django", lang: "Django/Jinja2" },
  { markup: "dns-zone", lang: "DNS zone file", isAlias: true },
  { markup: "dns-zone-file", lang: "DNS zone file" },
  { markup: "docker", lang: "Docker" },
  { markup: "dockerfile", lang: "Docker", isAlias: true },
  { markup: "dot", lang: "DOT (Graphviz)" },
  { markup: "dotnet", lang: "C#", isAlias: true },
  { markup: "ebnf", lang: "EBNF" },
  { markup: "editorconfig", lang: "EditorConfig" },
  { markup: "eiffel", lang: "Eiffel" },
  { markup: "ejs", lang: "EJS" },
  { markup: "elisp", lang: "Lisp", isAlias: true },
  { markup: "elixir", lang: "Elixir" },
  { markup: "elm", lang: "Elm" },
  { markup: "emacs", lang: "Lisp", isAlias: true },
  { markup: "emacs-lisp", lang: "Lisp", isAlias: true },
  { markup: "erb", lang: "ERB" },
  { markup: "erlang", lang: "Erlang" },
  { markup: "eta", lang: "EJS", title: "Eta", isAlias: true },
  { markup: "etlua", lang: "Embedded Lua templating" },
  { markup: "excel-formula", lang: "Excel Formula" },
  { markup: "factor", lang: "Factor" },
  { markup: "false", lang: "False" },
  { markup: "firestore-security-rules", lang: "Firestore security rules" },
  { markup: "flow", lang: "Flow" },
  { markup: "fortran", lang: "Fortran" },
  { markup: "fsharp", lang: "F#" },
  { markup: "ftl", lang: "FreeMarker Template Language" },
  { markup: "g4", lang: "ANTLR4", isAlias: true },
  { markup: "gamemakerlanguage", lang: "GameMaker Language", isAlias: true },
  { markup: "gap", lang: "GAP (CAS)" },
  { markup: "gawk", lang: "AWK", title: "GAWK", isAlias: true },
  { markup: "gcode", lang: "G-code" },
  { markup: "gdscript", lang: "GDScript" },
  { markup: "gedcom", lang: "GEDCOM" },
  { markup: "gettext", lang: "gettext" },
  { markup: "gherkin", lang: "Gherkin" },
  { markup: "git", lang: "Git" },
  { markup: "gitignore", lang: ".ignore", title: ".gitignore", isAlias: true },
  { markup: "glsl", lang: "GLSL" },
  { markup: "gml", lang: "GameMaker Language" },
  { markup: "gn", lang: "GN" },
  { markup: "gni", lang: "GN", isAlias: true },
  { markup: "go", lang: "Go" },
  { markup: "go-mod", lang: "Go module", isAlias: true },
  { markup: "go-module", lang: "Go module" },
  { markup: "gradle", lang: "Gradle" },
  { markup: "graphql", lang: "GraphQL" },
  { markup: "groovy", lang: "Groovy" },
  { markup: "gv", lang: "DOT (Graphviz)", isAlias: true },
  { markup: "haml", lang: "Haml" },
  { markup: "handlebars", lang: "Handlebars" },
  { markup: "haskell", lang: "Haskell" },
  { markup: "haxe", lang: "Haxe" },
  { markup: "hbs", lang: "Handlebars", isAlias: true },
  { markup: "hcl", lang: "HCL" },
  { markup: "hgignore", lang: ".ignore", title: ".hgignore", isAlias: true },
  { markup: "hlsl", lang: "HLSL" },
  { markup: "hoon", lang: "Hoon" },
  { markup: "hpkp", lang: "HTTP Public-Key-Pins" },
  { markup: "hs", lang: "Haskell", isAlias: true },
  { markup: "hsts", lang: "HTTP Strict-Transport-Security" },
  { markup: "html", lang: "Markup", title: "HTML", isAlias: true },
  { markup: "http", lang: "HTTP" },
  { markup: "ichigojam", lang: "IchigoJam" },
  { markup: "icon", lang: "Icon" },
  { markup: "icu-message-format", lang: "ICU Message Format" },
  { markup: "idr", lang: "Idris", isAlias: true },
  { markup: "idris", lang: "Idris" },
  { markup: "iecst", lang: "Structured Text (IEC 61131-3)" },
  { markup: "ignore", lang: ".ignore" },
  { markup: "inform7", lang: "Inform 7" },
  { markup: "ini", lang: "Ini" },
  { markup: "ino", lang: "Arduino", isAlias: true },
  { markup: "io", lang: "Io" },
  { markup: "j", lang: "J" },
  { markup: "java", lang: "Java" },
  { markup: "javadoc", lang: "JavaDoc" },
  { markup: "javadoclike", lang: "JavaDoc-like" },
  { markup: "javascript", lang: "JavaScript" },
  { markup: "javastacktrace", lang: "Java stack trace" },
  { markup: "jexl", lang: "Jexl" },
  { markup: "jinja2", lang: "Django/Jinja2", isAlias: true },
  { markup: "jolie", lang: "Jolie" },
  { markup: "jq", lang: "JQ" },
  { markup: "js", lang: "JavaScript", isAlias: true },
  { markup: "js-templates", lang: "JS Templates" },
  { markup: "jsdoc", lang: "JSDoc" },
  { markup: "json", lang: "JSON" },
  { markup: "json5", lang: "JSON5" },
  { markup: "jsonp", lang: "JSONP" },
  { markup: "jsstacktrace", lang: "JS stack trace" },
  { markup: "jsx", lang: "React JSX" },
  { markup: "julia", lang: "Julia" },
  { markup: "keepalived", lang: "Keepalived Configure" },
  { markup: "keyman", lang: "Keyman" },
  { markup: "kotlin", lang: "Kotlin" },
  { markup: "kt", lang: "Kotlin", isAlias: true },
  { markup: "kts", lang: "Kotlin", title: "Kotlin Script", isAlias: true },
  { markup: "kum", lang: "KuMir (КуМир)", isAlias: true },
  { markup: "kumir", lang: "KuMir (КуМир)" },
  { markup: "kusto", lang: "Kusto" },
  { markup: "latex", lang: "LaTeX" },
  { markup: "latte", lang: "Latte" },
  { markup: "ld", lang: "GNU Linker Script", isAlias: true },
  { markup: "less", lang: "Less" },
  { markup: "lilypond", lang: "LilyPond" },
  { markup: "linker-script", lang: "GNU Linker Script" },
  { markup: "liquid", lang: "Liquid" },
  { markup: "lisp", lang: "Lisp" },
  { markup: "livescript", lang: "LiveScript" },
  { markup: "llvm", lang: "LLVM IR" },
  { markup: "log", lang: "Log file" },
  { markup: "lolcode", lang: "LOLCODE" },
  { markup: "lua", lang: "Lua" },
  { markup: "ly", lang: "LilyPond", isAlias: true },
  { markup: "magma", lang: "Magma (CAS)" },
  { markup: "makefile", lang: "Makefile" },
  { markup: "markdown", lang: "Markdown" },
  { markup: "markup", lang: "Markup" },
  { markup: "mata", lang: "Mata" },
  {
    markup: "mathematica",
    lang: "Wolfram language",
    title: "Mathematica",
    isAlias: true,
  },
  { markup: "mathml", lang: "Markup", title: "MathML", isAlias: true },
  { markup: "matlab", lang: "MATLAB" },
  { markup: "maxscript", lang: "MAXScript" },
  { markup: "md", lang: "Markdown", isAlias: true },
  { markup: "mel", lang: "MEL" },
  { markup: "mermaid", lang: "Mermaid" },
  { markup: "metafont", lang: "METAFONT" },
  { markup: "mizar", lang: "Mizar" },
  { markup: "mongodb", lang: "MongoDB" },
  { markup: "monkey", lang: "Monkey" },
  { markup: "moon", lang: "MoonScript", isAlias: true },
  { markup: "moonscript", lang: "MoonScript" },
  { markup: "mscript", lang: "PowerQuery", isAlias: true },
  { markup: "mustache", lang: "Handlebars", title: "Mustache", isAlias: true },
  { markup: "n1ql", lang: "N1QL" },
  { markup: "n4js", lang: "N4JS" },
  { markup: "n4jsd", lang: "N4JS", isAlias: true },
  { markup: "nand2tetris-hdl", lang: "Nand To Tetris HDL" },
  { markup: "nani", lang: "Naninovel Script", isAlias: true },
  { markup: "naniscript", lang: "Naninovel Script" },
  { markup: "nasm", lang: "NASM" },
  {
    markup: "nb",
    lang: "Wolfram language",
    title: "Mathematica Notebook",
    isAlias: true,
  },
  { markup: "neon", lang: "NEON" },
  { markup: "nevod", lang: "Nevod" },
  { markup: "nginx", lang: "nginx" },
  { markup: "nim", lang: "Nim" },
  { markup: "nix", lang: "Nix" },
  { markup: "npmignore", lang: ".ignore", title: ".npmignore", isAlias: true },
  { markup: "nsis", lang: "NSIS" },
  { markup: "objc", lang: "Objective-C", isAlias: true },
  { markup: "objectivec", lang: "Objective-C" },
  {
    markup: "objectpascal",
    lang: "Pascal",
    title: "Object Pascal",
    isAlias: true,
  },
  { markup: "ocaml", lang: "OCaml" },
  { markup: "odin", lang: "Odin" },
  { markup: "opencl", lang: "OpenCL" },
  { markup: "opencl-extensions", lang: "OpenCL Extensions" },
  { markup: "openqasm", lang: "OpenQasm" },
  {
    markup: "oscript",
    lang: "BSL (1C:Enterprise)",
    title: "OneScript",
    isAlias: true,
  },
  { markup: "oz", lang: "Oz" },
  { markup: "parigp", lang: "PARI/GP" },
  { markup: "parser", lang: "Parser" },
  { markup: "pascal", lang: "Pascal" },
  { markup: "pascaligo", lang: "Pascaligo" },
  { markup: "pbfasm", lang: "PureBasic", isAlias: true },
  { markup: "pcaxis", lang: "PC-Axis" },
  { markup: "pcode", lang: "PeopleCode", isAlias: true },
  { markup: "peoplecode", lang: "PeopleCode" },
  { markup: "perl", lang: "Perl" },
  { markup: "php", lang: "PHP" },
  { markup: "php-extras", lang: "PHP Extras" },
  { markup: "phpdoc", lang: "PHPDoc" },
  { markup: "plain", lang: "Plain text" },
  { markup: "plaintext", lang: "Plain text", isAlias: true },
  { markup: "plant-uml", lang: "PlantUML" },
  { markup: "plantuml", lang: "PlantUML", isAlias: true },
  { markup: "plsql", lang: "PL/SQL" },
  { markup: "po", lang: "gettext", isAlias: true },
  { markup: "powerquery", lang: "PowerQuery" },
  { markup: "powershell", lang: "PowerShell" },
  { markup: "pq", lang: "PowerQuery", isAlias: true },
  { markup: "processing", lang: "Processing" },
  { markup: "prolog", lang: "Prolog" },
  { markup: "promql", lang: "PromQL" },
  { markup: "properties", lang: ".properties" },
  { markup: "protobuf", lang: "Protocol Buffers" },
  { markup: "psl", lang: "PATROL Scripting Language" },
  { markup: "pug", lang: "Pug" },
  { markup: "puppet", lang: "Puppet" },
  { markup: "pure", lang: "Pure" },
  { markup: "purebasic", lang: "PureBasic" },
  { markup: "purescript", lang: "PureScript" },
  { markup: "purs", lang: "PureScript", isAlias: true },
  { markup: "px", lang: "PC-Axis", isAlias: true },
  { markup: "py", lang: "Python", isAlias: true },
  { markup: "python", lang: "Python" },
  { markup: "q", lang: "Q (kdb+ database)" },
  { markup: "qasm", lang: "OpenQasm", isAlias: true },
  { markup: "qml", lang: "QML" },
  { markup: "qore", lang: "Qore" },
  { markup: "qs", lang: "Q#", isAlias: true },
  { markup: "qsharp", lang: "Q#" },
  { markup: "r", lang: "R" },
  { markup: "racket", lang: "Racket" },
  { markup: "razor", lang: "Razor C#", isAlias: true },
  { markup: "rb", lang: "Ruby", isAlias: true },
  { markup: "rbnf", lang: "BNF", title: "RBNF", isAlias: true },
  { markup: "reason", lang: "Reason" },
  { markup: "regex", lang: "Regex" },
  { markup: "rego", lang: "Rego" },
  { markup: "renpy", lang: "Ren'py" },
  { markup: "res", lang: "ReScript", isAlias: true },
  { markup: "rescript", lang: "ReScript" },
  { markup: "rest", lang: "reST (reStructuredText)" },
  { markup: "rip", lang: "Rip" },
  { markup: "rkt", lang: "Racket", isAlias: true },
  { markup: "roboconf", lang: "Roboconf" },
  { markup: "robot", lang: "Robot Framework", isAlias: true },
  { markup: "robotframework", lang: "Robot Framework" },
  { markup: "rpy", lang: "Ren'py", isAlias: true },
  { markup: "rq", lang: "SPARQL", isAlias: true },
  { markup: "rss", lang: "XML", title: "RSS", isAlias: true },
  { markup: "ruby", lang: "Ruby" },
  { markup: "rust", lang: "Rust" },
  { markup: "sas", lang: "SAS" },
  { markup: "sass", lang: "Sass (Sass)" },
  { markup: "scala", lang: "Scala" },
  { markup: "scheme", lang: "Scheme" },
  { markup: "sclang", lang: "SuperCollider", isAlias: true },
  { markup: "scss", lang: "Sass (SCSS)" },
  { markup: "sh", lang: "Bash", title: "Shell", isAlias: true },
  { markup: "sh-session", lang: "Shell session", isAlias: true },
  { markup: "shell", lang: "Bash", title: "Shell", isAlias: true },
  { markup: "shell-session", lang: "Shell session" },
  { markup: "shellsession", lang: "Shell session", isAlias: true },
  { markup: "shortcode", lang: "BBcode", title: "Shortcode", isAlias: true },
  { markup: "sln", lang: "Solution file", isAlias: true },
  { markup: "smali", lang: "Smali" },
  { markup: "smalltalk", lang: "Smalltalk" },
  { markup: "smarty", lang: "Smarty" },
  { markup: "sml", lang: "SML" },
  { markup: "smlnj", lang: "SML", title: "SML/NJ", isAlias: true },
  { markup: "sol", lang: "Solidity (Ethereum)", isAlias: true },
  { markup: "solidity", lang: "Solidity (Ethereum)" },
  { markup: "solution-file", lang: "Solution file" },
  { markup: "soy", lang: "Soy (Closure Template)" },
  { markup: "sparql", lang: "SPARQL" },
  { markup: "splunk-spl", lang: "Splunk SPL" },
  { markup: "sqf", lang: "SQF: Status Quo Function (Arma 3)" },
  { markup: "sql", lang: "SQL" },
  { markup: "squirrel", lang: "Squirrel" },
  { markup: "ssml", lang: "XML", title: "SSML", isAlias: true },
  { markup: "stan", lang: "Stan" },
  { markup: "stata", lang: "Stata Ado" },
  { markup: "stylus", lang: "Stylus" },
  { markup: "supercollider", lang: "SuperCollider" },
  { markup: "svg", lang: "Markup", title: "SVG", isAlias: true },
  { markup: "swift", lang: "Swift" },
  { markup: "systemd", lang: "Systemd configuration file" },
  { markup: "t4", lang: "T4 Text Templates (C#)", isAlias: true },
  { markup: "t4-cs", lang: "T4 Text Templates (C#)" },
  { markup: "t4-templating", lang: "T4 templating" },
  { markup: "t4-vb", lang: "T4 Text Templates (VB)" },
  { markup: "tap", lang: "TAP" },
  { markup: "tcl", lang: "Tcl" },
  { markup: "tex", lang: "LaTeX", title: "TeX", isAlias: true },
  { markup: "text", lang: "Plain text", isAlias: true },
  { markup: "textile", lang: "Textile" },
  { markup: "toml", lang: "TOML" },
  { markup: "tree-view", lang: "Treeview", isAlias: true },
  { markup: "treeview", lang: "Treeview" },
  { markup: "tremor", lang: "Tremor" },
  { markup: "trickle", lang: "Tremor", title: "trickle", isAlias: true },
  { markup: "trig", lang: "Turtle", title: "TriG", isAlias: true },
  { markup: "troy", lang: "Tremor", title: "troy", isAlias: true },
  { markup: "ts", lang: "TypeScript", isAlias: true },
  { markup: "tsconfig", lang: "TypoScript", title: "TSConfig", isAlias: true },
  { markup: "tsx", lang: "React TSX" },
  { markup: "tt2", lang: "Template Toolkit 2" },
  { markup: "turtle", lang: "Turtle" },
  { markup: "twig", lang: "Twig" },
  { markup: "txt", lang: "Plain text", isAlias: true },
  { markup: "typescript", lang: "TypeScript" },
  { markup: "typoscript", lang: "TypoScript" },
  { markup: "uc", lang: "UnrealScript", isAlias: true },
  { markup: "unrealscript", lang: "UnrealScript" },
  { markup: "uorazor", lang: "UO Razor Script" },
  { markup: "uri", lang: "URI" },
  { markup: "url", lang: "URI", title: "URL", isAlias: true },
  { markup: "uscript", lang: "UnrealScript", isAlias: true },
  { markup: "v", lang: "V" },
  { markup: "vala", lang: "Vala" },
  { markup: "vb", lang: "Visual Basic", isAlias: true },
  { markup: "vba", lang: "Visual Basic", title: "VBA", isAlias: true },
  { markup: "vbnet", lang: "VB.Net" },
  { markup: "velocity", lang: "Velocity" },
  { markup: "verilog", lang: "Verilog" },
  { markup: "vhdl", lang: "VHDL" },
  { markup: "vim", lang: "vim" },
  { markup: "visual-basic", lang: "Visual Basic" },
  { markup: "warpscript", lang: "WarpScript" },
  { markup: "wasm", lang: "WebAssembly" },
  { markup: "web-idl", lang: "Web IDL" },
  { markup: "webidl", lang: "Web IDL", isAlias: true },
  {
    markup: "webmanifest",
    lang: "JSON",
    title: "Web App Manifest",
    isAlias: true,
  },
  { markup: "wgsl", lang: "WGSL" },
  { markup: "wiki", lang: "Wiki markup" },
  { markup: "wl", lang: "Wolfram language", isAlias: true },
  { markup: "wolfram", lang: "Wolfram language" },
  { markup: "wren", lang: "Wren" },
  { markup: "xeora", lang: "Xeora" },
  { markup: "xeoracube", lang: "Xeora", title: "XeoraCube", isAlias: true },
  { markup: "xls", lang: "Excel Formula", isAlias: true },
  { markup: "xlsx", lang: "Excel Formula", isAlias: true },
  { markup: "xml", lang: "XML" },
  { markup: "xml-doc", lang: "XML doc (.net)" },
  { markup: "xojo", lang: "Xojo (REALbasic)" },
  { markup: "xquery", lang: "XQuery" },
  { markup: "yaml", lang: "YAML" },
  { markup: "yang", lang: "YANG" },
  { markup: "yml", lang: "YAML", isAlias: true },
  { markup: "zig", lang: "Zig" },
];
